#!/bin/bash 

echo "gc-ing" 
rm -rf *~ */*~ ; rm -rf errors.txt 

echo "making"
raco make */*.rkt

echo "testing" 
time raco test Common/*.rkt Players/*.rkt Admin/*.rkt 2> errors.txt
 
echo "grepping" 
if grep --quiet "non-zero exit" errors.txt; then 
   cat errors.txt 
else 
   tail -1 errors.txt
   grep location errors.txt
fi
